apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-main-db-alertmanager-main-0
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/mnt/kubernetes/monitoring/alertmanager"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu
  claimRef:
    kind: PersistentVolumeClaim
    namespace: monitoring
    name: alertmanager-main-db-alertmanager-main-0
    apiVersion: v1